<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<!--SafClassName="docSection1Title"--><!--SafTocEntry="7.6 Exception Gotchas"-->
<LINK REL="stylesheet" href="FILES/sbolM.css">
</HEAD>
<BODY link="#354278" vlink="#000066" alink="#000080" topmargin="0">
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#CCCCCC">
<td><font color="black" size=1>I l<font color="#FF0000">@</font>ve RuBoard</td>
<td valign="top" class="v2" align="right"><a href="lpython_snode83.html"><img src="FILES/previous.gif" width="62" height="15" border="0" align="absmiddle" alt="Previous Section"></a> <a href="lpython_snode85.html"><img src="FILES/next.gif" width="41" height="15" border="0" align="absmiddle" alt="Next Section"></a></td></table>
<FONT>
<h3>7.6
Exception Gotchas</h3>


<p>There isn't much to trip over here, but here are a few general
pointers on<a NAME="idx621"></a> <a naME="idx622"></A>
exception use.</P>




<h4>7.6.1
Exceptions Match by Identity, Not Equality</h4>


<p>As we've seen, when an exception is raised (by you or by Python
itself), Python searches for the most recently entered
<tT CLAss="monofont">try</tt> statement with a
<i>matching</i>
<a name="idx623"></a>
<a name="idx624"></a>
<a nAmE="idx625"></a>
<tt ClASs="monofont">except</TT> clause, where matching means the same
string object, the same class object, or a superclass of the raised
class object. It's important to notice that matching is
performed by identity, not equality. For instance, suppose we define
two string objects we want to raise as exceptions:</p>



<PrE CLAss="monofont">&gt;&gt;&gt; <b>ex1 = "spam"</b>
&gt;&gt;&gt; <B>ex2 = "spam"</B>
&gt;&gt;&gt;
&gt;&gt;&gt; <B>ex1 == ex2, ex1 is ex2</B>
(1, 0)</pre>


<p>Applying the <TT CLass="monofont">==</tT> test returns true (1) because they
have equal values, but <TT Class="monofont">is</tt> returns false (0) since
they are two distinct string objects in memory. Now, an
<tt class="monofont">except</tt> clause that names the same string object
will always match:</p>



<pre cLaSs="monofont">&gt;&gt;&gt; <b>try:</b>
...    <B>raise ex1</b>
... <B>except ex1:</B>
...    <b>print 'got it'</B>
...
got it</PrE>


<p>But one that lists an equal but not identical object will fail:</P>



<PRE clasS="monofont">&gt;&gt;&gt; <B>try:</B>
...    <B>raise ex1</b>
... <b>except ex2:</b>
...    <b>print 'Got it'</B>
...
Traceback (innermost last):
  File "&lt;stdin&gt;", line 2, in ?
spam</PRE>


<p>Here, the exception isn't caught, so Python climbs to the top
level of the process and prints a stack trace and the exception
automatically (the string <tt cLASS="monofont">"spam"</tt>). For class
exceptions, the behavior is similar, but Python generalizes the
notion of exception matching to include superclass relationships.</p>







<h4>7.6.2
Catching Too Much?</h4>


<p>Because Python lets you pick and choose which
<a name="idx626"></a>exceptions to catch, you sometimes
have to be careful to not be too inclusive. For example, you've
seen that an empty <tt class="monofont">except</tT> clause catches every
exception that might be raised while the code in the
<tT claSs="monofont">try</TT> block runs. Sometimes that's wanted, but
you may also wind up intercepting an error that's expected by a
<tT ClAsS="monofont">try</TT> handler higher up in a system. An exception
handler such as the following catches and stops every exception that
reaches it, whether or not another handler is waiting for it:</P>



<pre cLASS="monofont">try:
    ...
except:
 ...                          # everything comes here!</pre>


<p>The problem here is that you might not expect all the kinds of
exceptions that could occur during an operation:</P>



<PRE clasS="monofont">try:
    x = myditctionary[spam]     # oops: misspelled 
except:
    x = None                    # assume we got KeyError or IndexError</PRE>



<h5>7.6.2.1
Solution</h5>


<p>In this case, you're assuming the only sort of error that can
happen when indexing a dictionary is an indexing error. But because
the name <tt class="monofont">myditctionary</tt> is misspelled (you meant to
say <tt class="monofont">mydictionary</tT>), Python raises a
<tT claSs="monofont">NameError</TT> instead (since it's an undefined
name reference), which will be silently caught and ignored by your
handler. You should say: <tT ClAsS="monofont">except</TT>
<Tt claSS="monofont">(KeyError,</TT> <tt clASS="monofont">IndexError):</Tt> to make
your intentions explicit.</p>








<h4>7.6.3
Catching Too Little?</h4>


<P>Conversely, you<A NAme="idx627"></a> sometimes need to not be so exclusive.
When listing specific exceptions in a <tt class="monofont">try</tt>, you
catch only what you actually list. This isn't necessarily a bad
thing either, but if a system evolves to raise other exceptions in
the future, you may need to go back and add them to exception lists
elsewhere in the code. For instance, the following handler is written
to treat <tt class="monofont">myerror1</tT> and <tT claSs="monofont">myerror2</TT>
as normal cases and treat everything else as an error. If a
<tT ClAsS="monofont">myerror3</TT> is added in the future, it is processed
as an error unless you update the exception list:</P>



<pre cLASS="monofont">try:
  ...
except (myerror1, myerror2):    # what if I add a myerror3?
    ...                         # nonerrors
else:
    ...                         # assumed to be an error</pre>



<h5>7.6.3.1
Solution</H5>


<P>Careful use of class exceptions can make this gotcha go away
completely. As we saw earlier in this chapter, if you catch a general
superclass, you can add and raise more specific subclasses in the
future without having to extend <TT clasS="monofont">except</TT> clause
lists manually.</P>



<p>Whether you use classes here or not, a little design goes a long way.
The moral of the story is that you have to be careful not to be too
general or too specific in exception handlers. Especially in larger
systems, exception policies should be a part of the overall
design.<a name="idx628"></a>
<a name="idx629"></a></p>



</font>
 
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#CCCCCC">
<td><font color="black" size=1>I l<font color="#FF0000">@</font>ve RuBoard</td>
<td valign="top" class="v2" align="right"><a href="lpython_snode83.html"><img src="FILES/previous.gif" width="62" height="15" border="0" align="absmiddle" alt="Previous Section"></a> <a href="lpython_snode85.html"><img src="FILES/next.gif" width="41" height="15" border="0" align="absmiddle" alt="Next Section"></a></td></table>
</BODY></HTML>