<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<!--SafClassName="docSection1Title"--><!--SafTocEntry="7.5 Odds and Ends"-->
<LINK REL="stylesheet" href="FILES/sbolM.css">
</HEAD>
<BODY link="#354278" vlink="#000066" alink="#000080" topmargin="0">
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#CCCCCC">
<td><font color="black" size=1>I l<font color="#FF0000">@</font>ve RuBoard</td>
<td valign="top" class="v2" align="right"><a href="lpython_snode82.html"><img src="FILES/previous.gif" width="62" height="15" border="0" align="absmiddle" alt="Previous Section"></a> <a href="lpython_snode84.html"><img src="FILES/next.gif" width="41" height="15" border="0" align="absmiddle" alt="Next Section"></a></td></table>
<FONT>
<h3>7.5
Odds and Ends</h3>



<h4>7.5.1
Passing Optional Data</h4>


<P>As we've seen, <TT Class="monofont">raise</TT> statements can pass an
extra data item along with the exception for use in a handler. In
general,
the<A Name="idx613"></a> extra data allows you to send context
information to a handler. In fact, every exception has the extra
data; much like function results, it's the special
<TT CLass="monofont">None</tt> object if nothing was passed explicitly. The
following code illustrates:</p>



<pre class="monofont">myException = 'Error'              # string object

def raiser1():
    raise myException, "hello"     # raise, pass data

def raiser2():
    raise myException              # raise, None implied

def tryer(func):
    try:
        func()
    except myException, extraInfo:  # run func, catch exception + data
        print 'got this:', extraInfo

<b>% python</b>
&gt;&gt;&gt;<b> from helloexc import *</b>
&gt;&gt;&gt;<b> tryer(raiser1)              </b>    # gets explicitly passed extra data
got this: hello
&gt;&gt;&gt;<B> tryer(raiser2)             </b> # gets None by default
got this: None</Pre>






<h4>7.5.2
The assert Statement</H4>


<p>As a special case, Python 1.5 introduced an
<TT cLAsS="monofont">assert</tT>
<A NAme="idx614"></a> <a NAME="idx615"></a> statement, which is mostly syntactic
shorthand for a <tt cLASS="monofont">raise</tt>. A statement of the form:</p>



<pRE CLass="monofont">assert &lt;<tt class="monofont"><i>test</i></tt>&gt;, &lt;<tt clasS="monofont"><i>data</I></tt>&gt;          # the &lt;data&gt; part is optional</pRe>


<P>works like the following code:</P>



<pRE cLaSS="monofont">if __debug__:
    if not &lt;<TT clasS="monofont"><I>test</I></Tt>&gt;:
        raise AssertionError, &lt;<tt cLASS="monofont"><i>data</i></tt>&gt;</PRE>


<P>but <tt class="monofont">assert</tt> statements may be removed from the
compiled program's byte code if the <tt class="monofont">-O</tt>
command-line flag is used, thereby optimizing the program.
<tt ClAss="monofont">Assertion-Error</tT> is a built-in exception, and the _
_<tT ClASs="monofont">debug</Tt>__ flag is a built-in name which is
automatically set to 1 unless the <TT CLass="monofont">-O</tT> flag is used.
Assertions are typically used to verify program conditions during
development; when displayed, their message text includes source-code
line information automatically.</P>







<H4>7.5.3
Class Exceptions</H4>


<p>Recently, Python generalized the notion of <a naME="idx616"></A>
<A name="idx617"></A>exceptions. They may now also be
identified by classes and class instances. Like module packages and
private class attributes, class exceptions are an advanced topic you
can choose to use or not. If you're just getting started, you
may want to mark this section as optional reading.</P>



<P>So far we've used strings to identify our own exceptions; when
raised, Python matches the exception to <Tt class="monofont">except</tt>
clauses based on object identity (i.e., using the
<tt class="monofont">is</tt> test we saw in <a href="lpython_cnode17.html">Chapter 2</A>).
But when a class exception is raised, an <tt cLaSS="monofont">except</tT>
clause matches the current exception if it names the raised class or
a superclass of it. The upshot is that class exceptions support the
construction of exception hierarchies: by naming a general exception
superclass, an <Tt ClASS="monofont">except</Tt> clause can catch an entire
category of exceptions; any more specific subclass will match.</p>



<p>In general, user-defined exceptions may be identified by string or
class objects. Beginning with Python 1.5, all built-in exceptions
Python may raise are predefined class objects, instead of strings.
You normally won't need to care, unless you assume some
built-in exception is a string and try to concatenate it without
converting (e.g., <tT CLAss="monofont">KeyError</tt> <TT CLass="monofont">+</tT>
<TT Class="monofont">"spam"</tt>, versus <tt class="monofont">str(KeyError)</tt>
<tt claSs="monofont">+ "spam"</Tt>).</p>




<h5>7.5.3.1
General raise forms</H5>


<p>
<A NaME="idx618"></a>With the
addition of class-based exceptions, the <Tt CLASs="monofont">raise</tt>
statement can take the following five forms: the first two raise
string exceptions, the next two raise class exceptions, and the last
is an addition in Python Version 1.5, which simply reraises the
current exception (it's useful if you need to propagate an
arbitrary exception you've caught in a
<tT CLAss="monofont">except</tt> block). Raising an instance really raises
the instance's class; the instance is passed along with the
class as the extra data item (it's a good place to store
information for the handler).</P>



<PRE clasS="monofont">raise string          # matches except with same string object
raise string, data    # optional extra data (default=None)

raise class, instance # matches except with this class, or a superclass of it
raise instance        # same as: raise instance.__class__, instance

raise                 # re-raise the current exception (new in 1.5)</PRE>


<p>For backward compatibility with Python versions in which built-in
exceptions were strings, you can also use these forms of the
<tt class="monofont">raise</tt> statement:</p>



<pre class="monofont">raise class                     # same as: raise class()
raise class, arg                # all are really: raise instance
raise class, (arg, arg,...)</pRe>


<P>These are all the same as saying <tt cLaSS="monofont">raise</tT>
<Tt ClASS="monofont">class(arg...)</Tt>, and therefore the same as the
<tt cLASS="monofont">raise instance</tt> form above (Python calls the class
to create and raise an instance of it). For example, you may raise an
instance of the built-in <tt CLASs="monofont">KeyError</tt> exception by
saying simply <tT CLAss="monofont">raise</tt> <tt class="monofont">KeyError</tt>,
even though <tt class="monofont">KeyError</Tt> is now a class.</P>



<p>If that sounds confusing, just remember that exceptions may be
identified by string, class, or class instance objects, and you may
pass extra data with the exception or not. If the extra data you pass
with a class isn't an instance object, Python makes an instance
for you.</p>






<h5>7.5.3.2
Example</H5>


<p>Let's look at an example to see how class exceptions work. In
the following, we define a superclass <TT cLAsS="monofont">General</tT> and
one subclass of it called <TT Class="monofont">Specific</TT>. We're
trying to illustrate the notion of exception categories here;
handlers that catch <TT clasS="monofont">General</TT> will also catch a
subclass of it like <Tt claSS="monofont">Specific</TT>. We then create
functions that raise instances of both classes as exceptions and a
top-level <tt class="monofont">try</tt> that catches
<tt class="monofont">General</tt>; the same <tt ClAss="monofont">try</tT> catches
<tT ClASs="monofont">General</Tt> and <TT CLass="monofont">Specific</tT>
exceptions, because <TT Class="monofont">Specific</TT> is a subclass of
<TT clasS="monofont">General</TT>:</P>



<pre class="monofont">class General:           pass
class Specific(General): pass

def raiser1():
    X = General()         # raise listed class instance
    raise X

def raiser2():
    X = Specific()        # raise instance of subclass
    raise X

for func in (raiser1, raiser2):
    try:
        func()
    except General:               # match General or any subclass of it
        import sys
        print 'caught:', sys.exc_type

% <b>python classexc.py</b>
caught: &lt;class General at 881ee0&gt;
caught: &lt;class Specific at 881100&gt;</pre>


<p>Since there are only two possible exceptions here, this doesn't
really do justice to the utility of class exceptions; we can achieve
the same effects by coding a list of string exception names in the
<tt clasS="monofont">except</tT> (e.g., <tt cLaSS="monofont">except</tT>
<Tt ClASS="monofont">(a,</Tt> <tt cLASS="monofont">b,</tt> <tt CLASs="monofont">c):</tt>),
and passing along an instance object as the extra data item. But for
large or high exception hierarchies, it may be easier to catch
categories using classes than to list every member of a category in a
single <tT CLAss="monofont">except</tt> clause. Moreover, exception
hierarchies can be extended by adding new subclasses, without
breaking existing code.</p>



<p>For example, the built-in exception
<tt class="monofont">ArithmeticError</tt> is a superclass to more specific
exceptions such as <tt claSs="monofont">OverflowError</Tt> and
<tt ClASs="monofont">ZeroDivisionError</TT>, but catching just
<tT cLASS="monofont">ArithmeticError</tt> in a <tt CLASs="monofont">try</tt>, you
catch any more specific kind of numeric error subclass raised.
Furthermore, if you add new kinds of numeric error subclasses in the
future, existing code that catches the
<tT CLAss="monofont">ArithmeticError</tt> superclass (category) also catches
the new specific subclasses without modification; there's no
need to explicitly extend a list of exception names.</P>



<P>Besides supporting hierarchies, class exceptions also provide storage
for extra state information (as instance attributes), but this
isn't much more convenient than passing compound objects as
extra data with string exceptions (e.g., <TT class="monofont">raise</tt>
<tt class="monofont">string, object</tt>). As usual in Python, the choice to
use OOP or not is mostly yours to make.<a namE="idx619"></a> <A namE="idx620"></a></P>



</FoNT>
 
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#CCCCCC">
<td><font color="black" size=1>I l<font color="#FF0000">@</font>ve RuBoard</td>
<td valign="top" class="v2" align="right"><a href="lpython_snode82.html"><img src="FILES/previous.gif" width="62" height="15" border="0" align="absmiddle" alt="Previous Section"></a> <a href="lpython_snode84.html"><img src="FILES/next.gif" width="41" height="15" border="0" align="absmiddle" alt="Next Section"></a></td></table>
</BODY></HTML>