<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<!--SafClassName="docSection1Title"--><!--SafTocEntry="3.3 Error and Exception Handling"-->
<LINK REL="stylesheet" href="FILES/sbolM.css">
</HEAD>
<BODY link="#354278" vlink="#000066" alink="#000080" topmargin="0">
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#CCCCCC">
<td><font color="black" size=1>I l<font color="#FF0000">@</font>ve RuBoard</td>
<td valign="top" class="v2" align="right"><a href="0201379260_snode19.html"><img src="FILES/previous.gif" width="62" height="15" border="0" align="absmiddle" alt="Previous Section"></a> <a href="0201379260_snode21.html"><img src="FILES/next.gif" width="41" height="15" border="0" align="absmiddle" alt="Next Section"></a></td></table>
<FONT><h3>3.3
Error and Exception Handling</h3>
			<p>The C++ standard library is heterogeneous. It contains software from very different sources that have different styles of design and implementation. Error and exception handling is a typical example of these differences. Parts of the library, such as string classes, support detailed error handling. They check for every possible problem that might occur and throw an exception if there is an error. Other parts, such as the STL (the standard template library) and valarrays, prefer speed over safety, so they rarely check for logical errors and throw exceptions only if runtime errors occur.</p>

			<A NAMe="1"></a><h4>3.3.1
Standard Exception Classes</h4>
				<P>All exceptions thrown from the language or the library are derived from the base class <TT Class="monofont">exception.</TT> This class is the root of several standard exception classes that form a hierarchy, as shown in <A href="0201379260_snode20.html#2">Figure 3.1</a>. These standard exception classes can be divided into three groups:</p>

				<center>
					<h5>
<a name="2"></a>Figure 3.1.. Hierarchy of Standard Exceptions</h5><imG BORDEr="0" WIdTH="500" hEIGHT="336" src="FILES/03fig01.gif" alT="graphics/03fig01.gif"></CENter>

				<oL TYPe="1" staRT="restarts">
<LI><p>Exceptions for language support</p>
</li>
<li><p>Exceptions for the C++ standard library</p>
</li>
<li><p>Exceptions for errors outside the scope of a program</p>

					</li>
</ol>

				<h5>Exception Classes for Language Support</h5>
					<p>Exceptions for language support are used by language features. So in a way they are part of the core language rather than the library. These exceptions are thrown when the following operations fail.</P>

					<UL>
<LI><P>An exception of class <tT ClASs="monofont">bad_alloc</TT> is thrown whenever the global operator <TT CLass="monofont">new</tT> fails (except when the <TT Class="monofont">nothrow</TT> version of <TT clasS="monofont">new</TT> is used). This is probably the most important exception because it might occur at any time in any nontrivial program.</P>
</li>
<li><p>An exception of class <tt class="monofont">bad_cast</tt> is thrown by the <tt class="monofont">dynamic_cast</TT> operator if a type conversion on a reference fails at runtime. The <TT CLaSS="monofont">dynamic_cast</tT> operator is described on page 19.</P>
</lI>
<LI><P>An exception of class <TT clasS="monofont">bad_typeid</TT> is thrown by the <Tt claSS="monofont">typeid</TT> operator for runtime type identification. If the argument to <tt clASS="monofont">typeid</Tt> is zero or the null pointer, this exception gets thrown.</p>
</li>
<li><p>An exception of class <tt class="monofont">bad_exception</tt> is used to handle unexpected exceptions. It does this by using the function <tt claSS="monofont">unexpected(). unexpected()</TT> is called if a function throws an exception that is not listed in an exception specification (exception specifications are introduced on page 16). For example:</P>

							<PrE>
								
   class El;
   class E2;
   void f() throw(E1)       <I>//throws only exceptions of type</i> E1
   {
       ...
       throw El();          <I>//throws exception of type</I> El
       ...
       throw E2();          <i>//calls</I> unexpected(), <I>which calls</I> terminate()
   }
							</PRE>

							<p>The throw of an exception of type <tt cLASS="monofont">E2</tt> in <tt CLASs="monofont">f()</tt> violates the exception specification. In this case, the global function <tT CLAss="monofont">unexpected()</tt> gets called, which usually calls <tt class="monofont">terminate()</tt> to terminate the program. However, if class <tt class="monofont">bad_exception</tT> is part of the exception specification, then <TT CLAsS="monofont">unexpected()</Tt> usually rethrows an exception of this type:</P>

							<PrE>
								
   class El;
   class E2;


   void f() throw(E1, std::bad_exception)
                          <I>//throws exception of type</I> El <I>or</I>
                          //bad_exception <I>for any other exception type</i>
   {
      ...
      throw El();         <i>//throws exception of type</i> El
      ...
      throw E2();         <i>//calls</I> unexpected(), <I>which throws</I> bad_exception
   }
							</Pre>

							<p>Thus, if an exception specification includes the class <tT CLAss="monofont">bad_exception,</tt> then any exception not part of the specification may be replaced by <TT CLass="monofont">bad_exception</tt> within the function <tt class="monofont">unexpected().</tt><font sizE="1"><SUP><A HrEF="#FOOTNOTE-1">[1]</a></SUp></FONT>
</P>
<BlockQUOTe><fonT SIZe="1">
<p clASS="footnote">
<Sup><a name="FOOTNOTE-1">[1]</a></sup>
You can modify the exact behavior of <tt class="monofont">unexpected().</tt> However, a function never throws exceptions other than those stated in its exception specification (if any).</p>
</FONT></BLoCKqUOtE>

								
						</LI>
</UL>
				
				<H5>Exception Classes for the Standard Library</h5>
					<p>Exception classes for the C++ standard library are usually derived from class <tt CLASs="monofont">logic_error.</tt> Logic errors are errors that, at least in theory, could be avoided by the program; for example, by performing additional tests of function arguments. Examples of such errors are a violation of logical preconditions or a class invariant. The C++ standard library provides the following classes for logic errors:</p>

					<UL>
<LI><p>An exception of class <tt cLASS="monofont">invalid_argument</tt> is used to report invalid arguments, such as when a bitset (array of bits) is initialized with a char other than <tt class="monofont">'0'</tt> or <tt class="monofont">'1'.</tt></p>
</LI>
<LI><P>An exception of class <Tt CLaSS="monofont">length_error</tT> is used to report an attempt to do something that exceeds a maximum allowable size, such as appending too many characters to a string.</P>
</LI>
<LI><p>An exception of class <tt cLASS="monofont">out_of_range</tt> is used to report that an argument value is not in the expected range, such as when a wrong index is used in an array-like collection or string.</p>
</lI>
<LI><P>An exception of class <tt clASS="monofont">domain_error</Tt> is used to report a domain error.</p>

						</li>
</ul>
					<p>In addition, for the I/O part of the library, a special exception class called <tt class="monofont">ios_base::failure</tt> is provided. It may be thrown when a stream changes its state due to an error or end-of-file. The exact behavior of this exception class is described in <a href="0201379260_snode104.html#7">Section 13.4.4</A>.</P>

				
				<H5>Exception Classes for Errors Outside the Scope of a Program</H5>
					<P>Exceptions derived from <Tt CLaSS="monofont">runtime_error</tT> are provided to report events that are beyond the scope of a program and are not easily avoidable. The C++ standard library provides the following classes for runtime errors:</P>

					<UL>
<LI><p>An exception of class <tt cLASS="monofont">range_error</tt> is used to report a range error in internal computations.</p>
</lI>
<LI><P>An exception of class <tt clASS="monofont">overflow_error</Tt> is used to report an arithmetic overflow.</p>
</li>
<li><p>An exception of class <tt class="monofont">underflow_error</tt> is used to report an arithmetic underflow.</p>

						</li>
</ul>
				
				<H5>Exceptions Thrown by the Standard Library</H5>
					<P>The C++ standard library itself can produce exceptions of classes <TT ClASs="monofont">range_error, out_of_range,</TT> and <tT CLASS="monofont">invalid_argument.</tt> However, because language features as well as user code are used by the library, their functions might throw any exception indirectly. In particular, <tt CLASs="monofont">bad_alloc</tt> exceptions can be thrown whenever storage is allocated.</p>

					<P>Any implementation of the standard library might offer additional exception classes (either as siblings or as derived classes). However, the use of these nonstandard classes makes code non-portable because you could not use another implementation of the standard library without breaking your code. So, you should always use only the standard exception classes.</P>

				
				<H5>Header Files for Exception Classes</H5>
					<p>The base class exception and class <tt cLASS="monofont">bad_exception</tt> are defined in <tt class="monofont">&lt;exception&gt;.</tt> Class <tt class="monofont">bad_alloc</tt> is defined in <tT CLASS="monofont">&lt;new&gt;.</tT> Classes <Tt CLaSS="monofont">bad_cast</TT> and <TT clasS="monofont">bad_typeid</TT> are defined in <Tt claSS="monofont">&lt;typeinfo&gt;.</TT> Class <tt clASS="monofont">ios_base::failure</Tt> is defined in <tt class="monofont">&lt;ios&gt;.</tt> All other classes are defined in <tt class="monofont">&lt;stdexcept&gt;.</tt></p>

				
			
			<h4>3.3.2
Members of Exception Classes</H4>
				<P>To handle an exception in a <TT CLaSS="monofont">catch</tT> clause, you may use the exception interface. The interface of all standard exceptions classes contains only one member that can be used to get additional information besides the type itself: the member function <Tt CLASS="monofont">what(),</Tt> which returns a null-terminated byte string:</p>

				<prE>
					
   namespace std {
       class exception {
         public:
               virtual const char* what() const throw();
               ...
         };
   }

				</PRE>

				<p>The content of the string is implementation defined. It most likely (but not necessarily) determines the level of help and detail of such information. Note that the string might be a null-terminated multibyte string that is suitable to convert and display as <tt cLASS="monofont">wstring</tt> (<tt CLASs="monofont">wstrings</tt> are introduced in Section 2, page 480). The C-string, returned by <tt class="monofont">what(),</tt> is valid until the exception object from which it is obtained gets destroyed.<font size="1"><sUP><A HREf="#FOOTNOTE-2">[2]</A></SuP></FoNT>
</P>
<BLOckquOTE><Font sIZE="1">
<P clasS="footnote">
<SUP><a name="FOOTNOTE-2">[2]</a></sup>
The specification of the lifetime of the return value of <tt class="monofont">what()</tt> is not specified in the original standard. However, this is the proposed resolution to fix this problem.</p>
</foNT></BLOCkQUoTE>

					
				<p>The remaining members of the standard exception classes create, copy, assign, and destroy exception objects. Note that besides <TT CLASs="monofont">what()</tt> there is no additional member for any of the standard exception classes that describes the kind of exception. For example, there is no portable way to find out the context of an exception or the faulty index of a range error. Thus, a portable evaluation of an exception could only print the message returned from <tT CLAss="monofont">what():</tt></P>

				<PRE>
					
   try {
       ...
   }
   catch (const exception&amp; error) {
       <i>//print implementation-defined error message</i>
       cerr &lt;&lt; error.what() &lt;&lt; endl;
       ...
   }

				</prE>

				<P>The only other possible evaluation might be an interpretation of the exact type of the exception. For example, due to a <TT class="monofont">bad_alloc</tt> exception, a program might try to get more memory.</p>

			
			<h4>3.3.3
Throwing Standard Exceptions</h4>
				<p>You can throw standard exceptions inside your own library or program. All standard exception classes that enable you to do this have only one parameter to create the exception: a <tt class="monofont">string</tt> (class <tT CLASS="monofont">string</tT> is described in <A href="0201379260_cnode88.html">Chapter 11</A>) that will become the description returned by <TT CLAss="monofont">what().</tt> For example, the class <TT CLass="monofont">logic_error</tT> is defined as follows:</P>

				<PRe>
					
   namespace std {
       class logic_error : public exception {
         public:
           explicit logic_error (const string&amp; whatString);
       };
   }

				</pre>

				<P>The set of standard exceptions that provide this ability contains class <TT Class="monofont">logic_error</tt> and its derived classes, class <tt class="monofont">runtime_error</tt> and its derived classes, as well as class <tt clasS="monofont">ios_base::failure.</TT> Thus, you can't throw exceptions of the base class <TT ClASs="monofont">exception</TT> and any exception class that is provided for language support.</p>

				<P>To throw a standard exception, you simply create a string that describes the exception and use it to initialize the thrown exception object:</P>

				<PRE>
					
    string s;
    ...
    throw out_of_range(s);

				</Pre>

				<p>Implicit conversions from <tT CLAss="monofont">char*</tt> to <TT CLass="monofont">string</tT> exist, so you can also use a string literal directly:</P>

				<PRe>
					
    throw out_of_range("out_of_range exception (somewhere, somehow)");

				</pre>

			
			<h4>3.3.4
Deriving Standard Exception Classes</h4>
				<p>Another possibility for using the standard exception classes in your code is to define a special exception class derived directly or indirectly from class <tt class="monofont">exception.</tt> To do this, you must ensure that the <tt claSS="monofont">what()</TT> mechanism works.</P>

				<P>The member function <tT ClASs="monofont">what()</TT> is virtual. So, one way to provide <TT CLass="monofont">what()</tT> is to write your own implementation of <TT Class="monofont">what():</TT></P>

				<Pre>
					
   namespace MyLib {
       <i>/* user-defined exception class</i>
        <I>* derived from a standard class for exceptions</I>
        <I>*/</I>
       class MyProblem : public std::exception {
          public:
            ...
            MyProblem(...) {                     <i>//special constructor</i> 
            }


            virtual const char* what() const throw() {  <i>//</i>what()<i> function</i>
               ...
           }
       };
       ...


       void f() {
           ... 
           <i>//create an exception object and throw it</i>
               throw MyProblem(...);
               ...
       }
   }

				</pre>

				<p>Another way to provide the <tt class="monofont">what()</tt> function is to derive your exception class from one of the classes that have a string constructor for the <TT CLASs="monofont">what()</TT> argument:</p>

				<PRe>
					
    namespace MyLib {
        <I>/* user-defined exception class</I>
         <I>* - derived from a standard class for exceptions</I>
         <I>*   that has a constructor for the</I> what() <i>argument</i>
         <i>*/</i>
        class MyRangeProblem : public std::out_of_range {
          public:
            MyRangeProblem (const string&amp; whatString)
             : out_of_range(whatString) {
            }
        };
        ...


        void f() {
            ...
            <I>//create an exception object by using a string constructor and throw it</I>
            throw MyRangeProblem("here is my special range problem");
            ...
        }
   }

				</PRe>

				<p>For examples that are part of a complete program, see class <tt CLASs="monofont">Stack</tt> on page 441 and class <tT CLAss="monofont">Queue</tt> on page 450.</p>

			
		</font>
 
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#CCCCCC">
<td><font color="black" size=1>I l<font color="#FF0000">@</font>ve RuBoard</td>
<td valign="top" class="v2" align="right"><a href="0201379260_snode19.html"><img src="FILES/previous.gif" width="62" height="15" border="0" align="absmiddle" alt="Previous Section"></a> <a href="0201379260_snode21.html"><img src="FILES/next.gif" width="41" height="15" border="0" align="absmiddle" alt="Next Section"></a></td></table>
</BODY></HTML>